[package]
name = "static_map_macros"
version = "0.1.1"
authors = ["Christopher Breeden <github@u.breeden.cc>"]
description = "Compatibility-patched procedural macro for legacy static_map tables."
license = "MIT OR Apache-2.0"
repository = "https://github.com/cbreeden/static-map"
publish = false

[lib]
proc-macro = true

[dependencies]
fxhash = "0.1"
syn = "0.11"
quote = "0.3"
